-- Durable event buffer for the stateless hosted MCP transport. Every hosted
-- tools/call request appends normalized call/result events here; finalize_session
-- consumes them into sessions.metadata.transcript and deletes the buffer.

create table if not exists public.mcp_session_events (
  id bigint generated by default as identity primary key,
  session_key text not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  project_id uuid references public.projects(id) on delete cascade not null,
  event jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists mcp_session_events_lookup_idx
  on public.mcp_session_events (user_id, project_id, session_key, id);

alter table public.mcp_session_events enable row level security;

drop policy if exists "Users can manage own MCP session events" on public.mcp_session_events;
create policy "Users can manage own MCP session events"
  on public.mcp_session_events
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

comment on table public.mcp_session_events is
  'Short-lived normalized MCP call/result events consumed when a hosted Axis session is finalized.';
