-- Unit-economics guardrails for the paid intelligence layer.
--
-- Two tables, both written only with the service role:
--
-- 1. embedding_cache — content-addressed cache of query embeddings. Agents
--    call search in loops with recurring queries; re-embedding the same input
--    is pure token burn. Keyed by sha256(model || input).
-- 2. inference_events — one row per model call (embed / expand / rerank /
--    synthesis) with real token counts and estimated USD cost. This is both
--    the cost-telemetry stream and the source of truth for per-org daily and
--    monthly budget enforcement in lib/inference.ts.
--
-- orgs / org_members / projects are created outside the numbered migration
-- chain (see 0008), so all references to them are guarded with to_regclass —
-- this file must apply cleanly on a bare 0001..0010 database AND on prod.

create table if not exists public.embedding_cache (
  input_hash text primary key,
  model text not null,
  embedding jsonb not null,
  input_tokens integer not null default 0,
  hits integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_used_at timestamp with time zone default timezone('utc'::text, now()) not null
);

comment on table public.embedding_cache is
  'Content-addressed query-embedding cache (sha256(model||input) -> vector). Service-role only.';

-- Eviction support: cheap "purge least-recently-used" sweeps.
create index if not exists embedding_cache_last_used_idx
  on public.embedding_cache (last_used_at);

alter table public.embedding_cache enable row level security;

create table if not exists public.inference_events (
  id bigint generated by default as identity primary key,
  org_id uuid,
  user_id uuid references public.profiles(id) on delete cascade not null,
  project_id uuid,
  endpoint text not null,
  purpose text not null, -- 'embed' | 'expand' | 'rerank' | 'synthesis'
  model text not null,
  prompt_tokens integer not null default 0,
  completion_tokens integer not null default 0,
  cost_usd numeric(12, 8) not null default 0,
  cache_hit boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

comment on table public.inference_events is
  'Per-model-call cost telemetry; budget enforcement sums cost_usd per org/user per day and month.';

-- Budget lookups: "spend for this org since T" and the org-less fallback
-- "spend for this user since T".
create index if not exists inference_events_org_created_idx
  on public.inference_events (org_id, created_at);
create index if not exists inference_events_user_created_idx
  on public.inference_events (user_id, created_at);

alter table public.inference_events enable row level security;

-- Conditional FKs + member-read policy: only where orgs/projects exist.
do $$
begin
  if to_regclass('public.orgs') is not null then
    if not exists (
      select 1 from pg_constraint where conname = 'inference_events_org_id_fkey'
    ) then
      execute 'alter table public.inference_events
        add constraint inference_events_org_id_fkey
        foreign key (org_id) references public.orgs(id) on delete set null';
    end if;
  end if;

  if to_regclass('public.projects') is not null then
    if not exists (
      select 1 from pg_constraint where conname = 'inference_events_project_id_fkey'
    ) then
      execute 'alter table public.inference_events
        add constraint inference_events_project_id_fkey
        foreign key (project_id) references public.projects(id) on delete set null';
    end if;
  end if;

  if to_regclass('public.org_members') is not null then
    execute 'drop policy if exists "Org members can read org inference spend" on public.inference_events';
    execute 'create policy "Org members can read org inference spend"
      on public.inference_events
      for select
      using (
        user_id = auth.uid()
        or (
          org_id is not null
          and exists (
            select 1 from public.org_members m
            where m.org_id = inference_events.org_id
              and m.user_id = auth.uid()
          )
        )
      )';
  else
    execute 'drop policy if exists "Users can read own inference spend" on public.inference_events';
    execute 'create policy "Users can read own inference spend"
      on public.inference_events
      for select
      using (user_id = auth.uid())';
  end if;
end
$$;

-- Cache-hit bookkeeping without a read-modify-write round trip.
create or replace function public.touch_embedding_cache(p_input_hash text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.embedding_cache
  set hits = hits + 1,
      last_used_at = timezone('utc'::text, now())
  where input_hash = p_input_hash;
$$;

-- Fast budget check: sum of spend for an org (or org-less user) since a
-- timestamp, in one round trip.
create or replace function public.inference_spend_since(
  p_org_id uuid,
  p_user_id uuid,
  p_since timestamp with time zone
) returns numeric
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(sum(cost_usd), 0)
  from public.inference_events
  where created_at >= p_since
    and (
      (p_org_id is not null and org_id = p_org_id)
      or (p_org_id is null and org_id is null and user_id = p_user_id)
    );
$$;
